# Generated by Django 2.2.12 on 2020-04-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200426_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreports',
            name='reported',
        ),
    ]
