# Generated by Django 2.2.12 on 2020-04-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200423_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reported',
        ),
    ]
