# Generated by Django 2.2.12 on 2020-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(default='projects/nocover.jpg', upload_to='projects/covers'),
        ),
    ]
