# Generated by Django 2.2.12 on 2020-04-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200427_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/noimage.png', upload_to='categories/images'),
        ),
    ]
